feat: OS detection
IIC1103/mimir-testcase-uploader pull request #2
Opened 2022-03-07 00:30 UTC by Baelfire18

This feature autodetect de OS that way there is no need to comments and discomments in a cumbersome way
It was based in the oficial [documentation of the library](https://docs.python.org/3/library/platform.html#platform.system)

2022-03-07 02:15 UTC, nmassardot requested changes
Dime que opinai de las sugerencias. Y mantengamos las comillas dobles o las comillas simples, pero mantengamos solo unas 👍🏻

2022-03-07 02:15 UTC, nmassardot commented on uploader.py
> +
Según las docs, si es que no logra identificar el OS va a retornar un string vacío, eso haría que no se inicializara la variable y se caería el código de abajo 😮 sería peluo que pase, pero mejor prevenir que lamentar

2022-03-07 02:15 UTC, nmassardot commented on uploader.py
> +
Lo otro, quizás se podría usar algo tipo
```suggestion
OS = platform.system() 
if OS in ['Linux', 'Java', 'Windows']:
	key_command = Keys.CONTROL
elif OS == "Darwin":
	key_command = Keys.COMMAND
```
Así no teni que repetir código más abajo (no se me ocurrió un mejor nombre, tengo sueño y jet lag, lo siento)

2022-03-12 23:54 UTC, benjavicente approved these changes
Se ve bien!

2022-03-13 01:58 UTC, IgnacioPorte approved these changes
Se ve ok todo

2022-03-13 01:58 UTC, merged